openapi: "3.0.3"
info:
  version: "0.0.1" 
  title: "BotPlace API"
  
  termsOfService: https://primecontrol.com.br
  contact:
     email: jones.sabino@primecontrol.com.br
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: 'https://github.com/JoneSabino/botplace/blob/0678f792d0054e6dfd23fffee1ecfa985e1ebc6b/Logo_Normal%20vertical.png'
  description: Versão em desenvolvimento da API de consulta de faturas da Prime Control. \n\n 
               Saiba mais sobre a Prime Control em [https://primecontrol.com.br](https://primecontrol.com.br).
  
tags:
  - name: Definition
    description: Recursos relacionados às definições(configurações individuais) do cliente
  - name: Task
    description: Recursos relacionados às instancias dos robôs do cliente
externalDocs:
  description: Saiba mais
  url: http://prime.readthedocs.io
servers:
  - url: "https://kqe9jp3br0.execute-api.us-east-2.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: botplace
        description: Customer ID assigned by the service provider
components:
  schemas:
    task_start:
      type: object
      properties:
        task_name:
          type: string
        config:
          type: object
    task_stop:
      type: object
      properties:
        task_id:
          type: string
    task_config:
      type: object
      properties:
        task_id:
          type: string
    task_config_response:
      type: object
      properties:
        config:
          type: object
    task_schedule:
      type: object
      properties:
        cron_exp:
          type: string
          example: 0 12 ? * FRI *
          description: www.cronmaker.com (ignorar o primeiro 0 da expressão)
    task_response:
      type: object
      properties:
        task_id:
          type: string
    task_metadata:
      type: object
      properties:
        task_name:
          type: string
        config:
          type: object
        started:
          type: string
          format: date-time
          description: data e hora de inicio
        finished:
          type: string
          format: date-time
          description: data e hora de termino
        status:  
          type: string
          enum:
           - running
           - completed
           - failed
           - stopped
        error_msg:
          type: string
          description: mensagem de erro, se houver      
  parameters:
    task_idParam:
      in: path
      name: task_id
      schema:
        type: string
      required: true

paths:
  /definition:
    get:
      tags:
        - Definition
      operationId: clientDefinition
      summary: Recupera as definições atuais do cliente
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/task_config_response"    
    patch:
      tags:
        - Definition
      operationId: changeClientDefinition
      summary: Altera as definições do cliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task_schedule"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/task_response"

                
  /task/start:
    post:
      tags:
        - Task
      operationId: startTask
      summary: Inicia a Execução do robô
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task_start"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/task_response"
  
  /task/stop:
    post:
      tags:
        - Task
      operationId: stopTask
      summary: Para a execução do robô
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task_stop"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/task_response"
                
 
  /task/{task_id}/config:
    get:
      tags:
        - Task
      operationId: configTest
      summary: Recupera as configurações da execução atual
      parameters:
       - $ref: '#/components/parameters/task_idParam'
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/task_config_response"

  
  /task/config/schedule:
    patch:
      tags:
        - Task
      operationId: scheduleTask
      summary: Altera as configurações de agendamento do robô
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task_schedule"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/task_response"
 
  /task/{task_id}:
   get:
     tags:
      - Task
     operationId: task
     summary: Recupera informações sobre as execuções atuais
     parameters:
       - $ref: '#/components/parameters/task_idParam'
     responses:
       "200":
         description: "200 response"
         content:
           application/json:
             schema:
               $ref: "#/components/schemas/task_metadata"
               
